name = "tes"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.186.1.209:2053"
UUID = "e053b9a9-7777-4f23-85fa-c2a403f0a2c1"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
PROXYIP = "51.79.158.126,443"
