name = "user"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.186.1.209:2053"
UUID = "9d078aba-7a47-4f1c-90cf-36a55e24df39"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
