name = "admin"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.186.1.209:2053"
UUID = "996f9f6e-6134-40bc-8528-009f7ddb28a3"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
