name = "my-worker"  # otomatis1
type = "javascript"

account_id = "a3583fdfdeb73d41df62e801be6ece04"  # Ganti dengan Account ID Anda
zone_id = "d65078e43dbc7be09d9e019fc1201012"   # Ganti dengan Zone ID Anda
workers_dev = true  # Jika ingin menggunakan subdomain di workers.dev
route = ""  # Kosongkan jika tidak menggunakan route khusus
