name = "tes"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "103.186.1.209:2053"
UUID = "GENDAR"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
PROXYIP = "103.186.1.209:2053,103.168.146.169:20132"
